help_plus = """
Here are BanCodes :- 
✣ {VRx00} - SCAMMER.
✣ {VRx01} - SPAM ADDING MEMBER.
✣ {VRx03} - ABUSE SPAM.
✣ {VRx04} - NSFW SPAMMER.
✣ {VRx06} - IMPERSONATION.
✣ {VRx07} - MD/BTC SCAM.
✣ {VRx08} - ADDING SPAMBOTS.
✣ {VRx10} - ILLEGAL.
✣ {VRx11} - PHISHING.
✣ {VRx12} - FRAUD PROMOTION  [ANY KIND].
✣ {VRx13} - CYBER THREATENING / CYBER BULLY.
✣ {VRx14} - CHILD ABUSE.
✣ {VRx15} - BAN EVASION.
✣ {VRx16} - SPAMBOT.
✣ {VRx17} - RAID INITIALIZOR. 
✣ {VRx18} - RAID PARTICIPANT.
✣ {VRx19} - KRIMINALANT.
✣ {VRx20} - RAID/SPAM INFLAMMER.
✣ {RD-00} - RAID // SCAMMER BAN BY SCANNER BOT'S REPORTS
"""

__plugin_name__ = "bancodes"
